openapi: 3.0.0
info:
  title: User API V2
  description: User management API endpoints (Version 2)
  version: 2.0.0

paths:
  /users:
    post:
      summary: Create a new user (V2)
      description: Create a new user in the system with enhanced validation
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInputV2'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserV2'
        '400':
          description: Bad request
        '409':
          description: Email already taken
    get:
      summary: Get all users (V2)
      description: Get a list of all users with enhanced filtering and pagination
      tags:
        - Users
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Filter by user name
        - in: query
          name: role
          schema:
            type: string
          description: Filter by role
        - in: query
          name: email
          schema:
            type: string
          description: Filter by email
        - in: query
          name: sortBy
          schema:
            type: string
          description: Sort by field (format - field:desc/asc)
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          description: Maximum number of results per page
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Page number
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserV2'
                  page:
                    type: integer
                  limit:
                    type: integer
                  totalPages:
                    type: integer
                  totalResults:
                    type: integer

  /users/{userId}:
    get:
      summary: Get a user (V2)
      description: Get user information by ID with enhanced details
      tags:
        - Users
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserV2'
        '404':
          description: User not found
    patch:
      summary: Update a user (V2)
      description: Update user information with enhanced validation
      tags:
        - Users
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateV2'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserV2'
        '400':
          description: Bad request
        '404':
          description: User not found
    delete:
      summary: Delete a user (V2)
      description: Delete a user by ID with confirmation
      tags:
        - Users
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found

  /users/{userId}/roles:
    post:
      summary: Set user roles (V2)
      description: Assign roles to a user with enhanced validation
      tags:
        - Users
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleIds:
                  type: array
                  items:
                    type: string
              required:
                - roleIds
      responses:
        '200':
          description: Roles assigned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserV2'
        '400':
          description: Bad request
        '404':
          description: User not found

components:
  schemas:
    UserInputV2:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
        name:
          type: string
        roleId:
          type: string
        phone:
          type: string
          pattern: '^\\+?[1-9]\\d{1,14}$'
        address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            country:
              type: string
            zipCode:
              type: string
      required:
        - email
        - password
        - name
        - roleId

    UserUpdateV2:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
        name:
          type: string
        phone:
          type: string
          pattern: '^\\+?[1-9]\\d{1,14}$'
        address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            country:
              type: string
            zipCode:
              type: string

    UserV2:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        phone:
          type: string
        address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            country:
              type: string
            zipCode:
              type: string
        isEmailVerified:
          type: boolean
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleV2'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    RoleV2:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        permissions:
          type: array
          items:
            type: string
